name: "smartcity"
services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      mqtt_network:

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
      - path: ../default.env
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/structure.sql:/docker-entrypoint-initdb.d/structure.sql
    ports:
      - "5432:5432"
    networks:
      db_network:

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    env_file:
      - path: ../default.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      db_network:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      hub_redis:

  store:
    container_name: store
    build: ../store
    depends_on:
      - postgres_db
    restart: always
    env_file:
      - path: ../default.env
    ports:
      - "8000:8000"
    networks:
      hub_store:
      db_network:

  edge:
    container_name: edge
    build: ../edge
    depends_on:
      - mqtt
      - hub
    env_file:
      - path: ../default.env
    networks:
      mqtt_network:
      edge_hub:

  hub:
    container_name: hub
    build: ../hub
    depends_on:
      - mqtt
      - redis
      - store
    env_file:
      - path: ../default.env
    ports:
      - "9000:8000"
    networks:
      mqtt_network:
      hub_store:
      hub_redis:

  agent_car_1:
    container_name: agent_car_1
    build: ../agent
    depends_on:
      - mqtt
    env_file:
      - path: ../default.env
    environment:
      USER_ID: 1
      AGENT_TYPE: "car"
      DELAY: 1
    networks:
      mqtt_network:

  agent_traffic_light_1:
    container_name: agent_traffic_light_1
    build: ../agent
    depends_on:
      - mqtt
    env_file:
      - path: ../default.env
    environment:
      USER_ID: 2
      AGENT_TYPE: "traffic_light"
      DELAY: 30
      LATITUDE: 50.45029494727575
      LONTITUDE: 30.524486567396327
    networks:
      mqtt_network:

  agent_traffic_light_2:
    container_name: agent_traffic_light_2
    build: ../agent
    depends_on:
      - mqtt
    env_file:
      - path: ../default.env
    environment:
      USER_ID: 3
      AGENT_TYPE: "traffic_light"
      DELAY: 30
      LATITUDE: 50.45506951222323
      LONTITUDE: 30.52062624365189
    networks:
      mqtt_network:

  agent_traffic_light_3:
    container_name: agent_traffic_light_3
    build: ../agent
    depends_on:
      - mqtt
    env_file:
      - path: ../default.env
    environment:
      USER_ID: 4
      AGENT_TYPE: "traffic_light"
      DELAY: 30
      LATITUDE: 50.44778606866356
      LONTITUDE: 30.521873120186182
    networks:
      mqtt_network:

  agent_parking_space_1:
    container_name: agent_parking_space_1
    build: ../agent
    depends_on:
      - mqtt
    env_file:
      - path: ../default.env
    environment:
      USER_ID: 5
      AGENT_TYPE: "parking_space"
      DELAY: 60
      LATITUDE: 50.455430327362116
      LONTITUDE: 30.51994399239887
    networks:
      mqtt_network:

  agent_parking_space_2:
    container_name: agent_parking_space_2
    build: ../agent
    depends_on:
      - mqtt
    env_file:
      - path: ../default.env
    environment:
      USER_ID: 6
      AGENT_TYPE: "parking_space"
      DELAY: 60
      LATITUDE: 50.4535703820191
      LONTITUDE: 30.52123980825806
    networks:
      mqtt_network:

networks:
  mqtt_network:
  db_network:
  edge_hub:
  hub_store:
  hub_redis:

volumes:
  postgres_data:
  pgadmin-data:
