name: "road_vision"
services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      mqtt_network:


  agent_car_1:
    container_name: agent_car_1
    build: ../
    depends_on:
      - mqtt
    environment:
      USER_ID: 1
      AGENT_TYPE: "car"
      MQTT_BROKER_HOST: "mqtt"
      MQTT_BROKER_PORT: 1883
      MQTT_TOPIC: "agent_data_topic"
      DELAY: 1
    networks:
      mqtt_network:

  agent_traffic_light_1:
    container_name: agent_traffic_light_1
    build: ../
    depends_on:
      - mqtt
    environment:
      USER_ID: 2
      AGENT_TYPE: "traffic_light"
      MQTT_BROKER_HOST: "mqtt"
      MQTT_BROKER_PORT: 1883
      MQTT_TOPIC: "agent_data_topic"
      DELAY: 30
      LATITUDE: 50.45029494727575
      LONTITUDE: 30.524486567396327
    networks:
      mqtt_network:

  agent_parking_space_1:
    container_name: agent_parking_space_1
    build: ../
    depends_on:
      - mqtt
    environment:
      USER_ID: 3
      AGENT_TYPE: "parking_space"
      MQTT_BROKER_HOST: "mqtt"
      MQTT_BROKER_PORT: 1883
      MQTT_TOPIC: "agent_data_topic"
      DELAY: 60
      LATITUDE: 50.455430327362116
      LONTITUDE: 30.51994399239887
    networks:
      mqtt_network:


networks:
  mqtt_network:
